version: '3.7'

#volumes:
#  grafana_data: { }

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
#    volumes:
#      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_URL=postgres://USER:PASSWORD@IP:PORT/BATABASE
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
